### PR TITLE
Add mini scraps rule

### PR DESCRIPTION
**Pull request by bellesea**

### CODE REVIEW

**Comment by rutmanz** [comment]
Maybe define "mini-scrap." People seem to be confused as to what that term means

**Comment by polytroper** [comment]
Agreed, we need to say what that means.

**Comment by bellesea** [comment]
> Maybe define "mini-scrap." People seem to be confused as to what that term means

@rutmanz i agree, is it clearer now?

**Comment by rutmanz** [comment]
Yeah, that's pretty clear

**Review by polytroper — APPROVED** [review]

**Pull request merged**
