### PR TITLE
Fixed typo and improved grammar

### PR DESCRIPTION
**Pull request by radeeyate**
Title is self explanatory

### CODE REVIEW

**Comment by adammakesthingsdev** [comment]
not again 😭

**Comment by radeeyate** [comment]
It's annoying and grammatically incorrect, so I had no choice (this is something I do whenever I see grammar issues in git repos).

**Comment by adammakesthingsdev** [comment]
wait is this serious

**Comment by radeeyate** [comment]
Yes, I'm being serious.

**Comment by radeeyate** [comment]
Yes, I'm being serious.

**Comment by adammakesthingsdev** [comment]
It's not a typo of arcade, arcane is a word lol, it means secretive or mystical. That is absolutely a grammatically correct sentence

**Comment by adammakesthingsdev** [comment]
It's a weird word choice but it's funny and accurate

**Comment by radeeyate** [comment]
I'm aware it's a word, but wasn't aware it was a typo here. Shall I close this?

**Pull request closed without merging**
